# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-24 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulFoodApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='shop_logo/')),
                ('price', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=500)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_soldout', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soulFoodApp.Shop')),
            ],
        ),
    ]
