# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-24 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulFoodApp', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='size',
            new_name='quantity_per_package',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='shop_logo/'),
        ),
    ]
